spring:
  # DB 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  # 페이징 기본값 설정
  data:
    web:
      pageable:
        default-page-size: 15
  
  profiles:
    active: secret

# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie
  port: 8085
  tomcat:
    keep-alive-timeout: 300

# 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
