spring:
  profiles:
    default: secret-local
    include: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # open-in-view error remove
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  # 페이징 기본값 설정
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true


# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie
  port: 8085
  tomcat:
    keep-alive-timeout: 300

# 로깅 레벨 설정
logging:
  level:
    # AWS 연결 오류 로그 안 띄우고 개발 환경에서 부트 빠르게 띄우는 설정
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      springframework:
        web:
          client:
            RestTemplate: DEBUG